import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartProvider, { CartContext } from "@/presentation/context/CartContext";
import Summary from "@/presentation/component/Summary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {children}
          <Summary />
        </CartProvider>
      </body>
    </html>
  );
}
